# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'edu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for edu
  pod 'TesseractOCRiOS', '4.0.0'
  pod 'RNSound', :path => '../node_modules/react-native-sound'

  end

