# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'edU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for edU
    pod 'Sketch'
    pod 'Firebase/Core'
    pod 'Firebase/MLVision'
    # If using an on-device API:
    pod 'Firebase/MLVisionTextModel'

  target 'edUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'edUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
